"""initial unified users with id-only attribution

Revision ID: 3f666a538756
Revises: 
Create Date: 2025-09-10 02:03:01.357278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f666a538756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('day_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_session_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_day_session_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_day_session_is_closed'), ['is_closed'], unique=False)
        batch_op.create_index(batch_op.f('ix_day_session_start_time'), ['start_time'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('visible_for', sa.String(length=20), nullable=True),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_index('uq_tables_name_active', ['name'], unique=True, sqlite_where=sa.text('is_archived = 0'))

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('served_by_user_id', sa.Integer(), nullable=True),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('day_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_session_id'], ['day_session.id'], ),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['served_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_day_session_id'), ['day_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_is_completed'), ['is_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_opened_by_user_id'), ['opened_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_served_by_user_id'), ['served_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_table_id'), ['table_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantity >= 1', name='ck_order_items_quantity_min'),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_added_by_user_id'), ['added_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_status'), ['status'], unique=False)

    op.create_table('partial_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('cashier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cashier_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partial_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partial_payments_cashier_user_id'), ['cashier_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partial_payments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partial_payments_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_partial_payments_payment_method'), ['payment_method'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partial_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partial_payments_payment_method'))
        batch_op.drop_index(batch_op.f('ix_partial_payments_paid_at'))
        batch_op.drop_index(batch_op.f('ix_partial_payments_order_id'))
        batch_op.drop_index(batch_op.f('ix_partial_payments_cashier_user_id'))

    op.drop_table('partial_payments')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_status'))
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_added_by_user_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_table_id'))
        batch_op.drop_index(batch_op.f('ix_orders_served_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_opened_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_is_completed'))
        batch_op.drop_index(batch_op.f('ix_orders_day_session_id'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_index('uq_tables_name_active', sqlite_where=sa.text('is_archived = 0'))

    op.drop_table('tables')
    op.drop_table('users')
    op.drop_table('regions')
    op.drop_table('product')
    with op.batch_alter_table('day_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_session_start_time'))
        batch_op.drop_index(batch_op.f('ix_day_session_is_closed'))
        batch_op.drop_index(batch_op.f('ix_day_session_end_time'))
        batch_op.drop_index(batch_op.f('ix_day_session_date'))

    op.drop_table('day_session')
    # ### end Alembic commands ###
