"""add user.last_login

Revision ID: 70380ad9da5a
Revises: c50fd7b21859
Create Date: 2025-09-11 08:11:08.556618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70380ad9da5a'
down_revision = 'c50fd7b21859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.alter_column('is_on_shift',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_on_shift',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
